"""Add manual and health_connect columns

Revision ID: c6b96dbf29fe
Revises: 0005_activity_recording_status
Create Date: 2026-08-21 23:36:44.038857
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'c6b96dbf29fe'
down_revision: str | Sequence[str] | None = '0005_activity_recording_status'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('steps_manual', sa.Float(), nullable=True))
    op.add_column('activities', sa.Column('steps_health_connect', sa.Float(), nullable=True))
    op.add_column('activities', sa.Column('active_minutes_manual', sa.Float(), nullable=True))
    op.add_column('activities', sa.Column('active_minutes_health_connect', sa.Float(), nullable=True))
    op.add_column('activities', sa.Column('distance_manual', sa.Float(), nullable=True))
    op.add_column('activities', sa.Column('distance_health_connect', sa.Float(), nullable=True))
    op.add_column('activities', sa.Column('calories_manual', sa.Float(), nullable=True))
    op.add_column('activities', sa.Column('calories_health_connect', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'calories_health_connect')
    op.drop_column('activities', 'calories_manual')
    op.drop_column('activities', 'distance_health_connect')
    op.drop_column('activities', 'distance_manual')
    op.drop_column('activities', 'active_minutes_health_connect')
    op.drop_column('activities', 'active_minutes_manual')
    op.drop_column('activities', 'steps_health_connect')
    op.drop_column('activities', 'steps_manual')
    # ### end Alembic commands ###
