"""Phase 16 reconciliation columns

Revision ID: da9789b108a9
Revises: c6b96dbf29fe
Create Date: 2026-08-23 11:14:41.775820
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'da9789b108a9'
down_revision: str | Sequence[str] | None = 'c6b96dbf29fe'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('steps_downward_offset', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('activities', sa.Column('steps_provenance', sa.String(length=32), server_default='system', nullable=False))
    op.add_column('activities', sa.Column('steps_pending_reduction_value', sa.Float(), nullable=True))
    op.add_column('activities', sa.Column('steps_pending_reduction_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('activities', sa.Column('distance_downward_offset', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('activities', sa.Column('distance_provenance', sa.String(length=32), server_default='system', nullable=False))
    op.add_column('activities', sa.Column('distance_pending_reduction_value', sa.Float(), nullable=True))
    op.add_column('activities', sa.Column('distance_pending_reduction_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('activities', sa.Column('calories_downward_offset', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('activities', sa.Column('calories_provenance', sa.String(length=32), server_default='system', nullable=False))
    op.add_column('activities', sa.Column('calories_pending_reduction_value', sa.Float(), nullable=True))
    op.add_column('activities', sa.Column('calories_pending_reduction_at', sa.DateTime(timezone=True), nullable=True))

    op.execute("""
        UPDATE activities SET
        steps_downward_offset = GREATEST(COALESCE(steps_manual, 0), COALESCE(steps_health_connect, 0)) - COALESCE(steps_manual, 0),
        distance_downward_offset = GREATEST(COALESCE(distance_manual, 0), COALESCE(distance_health_connect, 0)) - COALESCE(distance_manual, 0),
        calories_downward_offset = GREATEST(COALESCE(calories_manual, 0), COALESCE(calories_health_connect, 0)) - COALESCE(calories_manual, 0)
        WHERE source = 'manual';
    """)
    op.execute("""
        UPDATE activities SET
        steps_provenance = CASE WHEN steps_downward_offset > 0 THEN 'blended' ELSE 'manual' END,
        distance_provenance = CASE WHEN distance_downward_offset > 0 THEN 'blended' ELSE 'manual' END,
        calories_provenance = CASE WHEN calories_downward_offset > 0 THEN 'blended' ELSE 'manual' END
        WHERE source = 'manual';
    """)
    op.execute("""
        UPDATE activities SET
        steps_provenance = 'health_connect',
        distance_provenance = 'health_connect',
        calories_provenance = 'health_connect'
        WHERE source = 'health_connect';
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'calories_pending_reduction_at')
    op.drop_column('activities', 'calories_pending_reduction_value')
    op.drop_column('activities', 'calories_provenance')
    op.drop_column('activities', 'calories_downward_offset')
    op.drop_column('activities', 'distance_pending_reduction_at')
    op.drop_column('activities', 'distance_pending_reduction_value')
    op.drop_column('activities', 'distance_provenance')
    op.drop_column('activities', 'distance_downward_offset')
    op.drop_column('activities', 'steps_pending_reduction_at')
    op.drop_column('activities', 'steps_pending_reduction_value')
    op.drop_column('activities', 'steps_provenance')
    op.drop_column('activities', 'steps_downward_offset')
    # ### end Alembic commands ###
